//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ClientWeb.Account {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegisterViewResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegisterViewResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalPrint.Infrastructure.Resources.ClientWeb.Account.RegisterViewResource", typeof(RegisterViewResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль и его подтверждение не совпадают..
        /// </summary>
        public static string ConfirmationNotEqualToPassword {
            get {
                return ResourceManager.GetString("ConfirmationNotEqualToPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на оферты.
        /// </summary>
        public static string ConfirmOfferLinkLabel {
            get {
                return ResourceManager.GetString("ConfirmOfferLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настоящим подтверждаю, что я ознакомлен и согласен с условиями.
        /// </summary>
        public static string ConfirmOfferLinkString {
            get {
                return ResourceManager.GetString("ConfirmOfferLinkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтобы завершить регистрацию, Вы должны подтвердить согласие с условиями оферты..
        /// </summary>
        public static string ConfirmOfferRequiredError {
            get {
                return ResourceManager.GetString("ConfirmOfferRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердите пароль.
        /// </summary>
        public static string ConfirmPasswordFieldLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Подтвердите пароль&quot; обязательно для заполнения..
        /// </summary>
        public static string ConfirmPasswordFieldRequiredError {
            get {
                return ResourceManager.GetString("ConfirmPasswordFieldRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Подтвердите пароль&quot; должно содержать корректный пароль..
        /// </summary>
        public static string ConfirmPasswordFieldTypeError {
            get {
                return ResourceManager.GetString("ConfirmPasswordFieldTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string EmailFieldLabel {
            get {
                return ResourceManager.GetString("EmailFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Email&quot; обязательно для заполнения..
        /// </summary>
        public static string EmailFieldRequiredError {
            get {
                return ResourceManager.GetString("EmailFieldRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Email&quot; должно содержать корректный email адрес..
        /// </summary>
        public static string EmailFieldTypeError {
            get {
                return ResourceManager.GetString("EmailFieldTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войдите.
        /// </summary>
        public static string LoginLinkLabel {
            get {
                return ResourceManager.GetString("LoginLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Есть аккаунт?.
        /// </summary>
        public static string LoginLinkString {
            get {
                return ResourceManager.GetString("LoginLinkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string PasswordFieldLabel {
            get {
                return ResourceManager.GetString("PasswordFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Минимальная длина пароля - {2} символов..
        /// </summary>
        public static string PasswordFieldMinLengthError {
            get {
                return ResourceManager.GetString("PasswordFieldMinLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Пароль&quot; обязательно для заполнения..
        /// </summary>
        public static string PasswordFieldRequiredError {
            get {
                return ResourceManager.GetString("PasswordFieldRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Пароль&quot; должно содержать корректный пароль..
        /// </summary>
        public static string PasswordFieldTypeError {
            get {
                return ResourceManager.GetString("PasswordFieldTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрироваться.
        /// </summary>
        public static string RegisterButtonLabel {
            get {
                return ResourceManager.GetString("RegisterButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string RegisterFormHeader {
            get {
                return ResourceManager.GetString("RegisterFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string RegisterFormTabTitle {
            get {
                return ResourceManager.GetString("RegisterFormTabTitle", resourceCulture);
            }
        }
    }
}
