//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ClientWeb.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegisterViewResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegisterViewResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalPrint.Infrastructure.Resources.ClientWeb.Account.RegisterViewResource", typeof(RegisterViewResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to и.
        /// </summary>
        public static string AndWord {
            get {
                return ResourceManager.GetString("AndWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль и его подтверждение не совпадают..
        /// </summary>
        public static string ConfirmationNotEqualToPassword {
            get {
                return ResourceManager.GetString("ConfirmationNotEqualToPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оферты.
        /// </summary>
        public static string ConfirmOfferLinkLabel {
            get {
                return ResourceManager.GetString("ConfirmOfferLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настоящим подтверждаю, что я ознакомлен и согласен с условиями.
        /// </summary>
        public static string ConfirmOfferLinkString {
            get {
                return ResourceManager.GetString("ConfirmOfferLinkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы завершить регистрацию, Вы должны подтвердить согласие с условиями оферты..
        /// </summary>
        public static string ConfirmOfferRequiredError {
            get {
                return ResourceManager.GetString("ConfirmOfferRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите пароль.
        /// </summary>
        public static string ConfirmPasswordFieldLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Подтвердите пароль&quot; обязательно для заполнения..
        /// </summary>
        public static string ConfirmPasswordFieldRequiredError {
            get {
                return ResourceManager.GetString("ConfirmPasswordFieldRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Подтвердите пароль&quot; должно содержать корректный пароль..
        /// </summary>
        public static string ConfirmPasswordFieldTypeError {
            get {
                return ResourceManager.GetString("ConfirmPasswordFieldTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailFieldLabel {
            get {
                return ResourceManager.GetString("EmailFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Email&quot; обязательно для заполнения..
        /// </summary>
        public static string EmailFieldRequiredError {
            get {
                return ResourceManager.GetString("EmailFieldRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Email&quot; должно содержать корректный email адрес..
        /// </summary>
        public static string EmailFieldTypeError {
            get {
                return ResourceManager.GetString("EmailFieldTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войдите.
        /// </summary>
        public static string LoginLinkLabel {
            get {
                return ResourceManager.GetString("LoginLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Есть аккаунт?.
        /// </summary>
        public static string LoginLinkString {
            get {
                return ResourceManager.GetString("LoginLinkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string PasswordFieldLabel {
            get {
                return ResourceManager.GetString("PasswordFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальная длина пароля - {2} символов..
        /// </summary>
        public static string PasswordFieldMinLengthError {
            get {
                return ResourceManager.GetString("PasswordFieldMinLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Пароль&quot; обязательно для заполнения..
        /// </summary>
        public static string PasswordFieldRequiredError {
            get {
                return ResourceManager.GetString("PasswordFieldRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Пароль&quot; должно содержать корректный пароль..
        /// </summary>
        public static string PasswordFieldTypeError {
            get {
                return ResourceManager.GetString("PasswordFieldTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Политикой Конфиденциальности.
        /// </summary>
        public static string PrivacyPolicyLinkLabel {
            get {
                return ResourceManager.GetString("PrivacyPolicyLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        public static string RegisterButtonLabel {
            get {
                return ResourceManager.GetString("RegisterButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string RegisterFormHeader {
            get {
                return ResourceManager.GetString("RegisterFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string RegisterFormTabTitle {
            get {
                return ResourceManager.GetString("RegisterFormTabTitle", resourceCulture);
            }
        }
    }
}
