//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ClientWeb.Order {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NewViewResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewViewResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalPrint.Infrastructure.Resources.ClientWeb.Order.NewViewResource", typeof(NewViewResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите файл.
        /// </summary>
        public static string ChooseFileButtonLabel {
            get {
                return ResourceManager.GetString("ChooseFileButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл для печати.
        /// </summary>
        public static string DocumentFieldLabel {
            get {
                return ResourceManager.GetString("DocumentFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация для печати.
        /// </summary>
        public static string FormHeaderText {
            get {
                return ResourceManager.GetString("FormHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ на печать.
        /// </summary>
        public static string FormTabTitle {
            get {
                return ResourceManager.GetString("FormTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Печать.
        /// </summary>
        public static string PrintButtonLabel {
            get {
                return ResourceManager.GetString("PrintButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цветная печать.
        /// </summary>
        public static string PrintColorLabel {
            get {
                return ResourceManager.GetString("PrintColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарий.
        /// </summary>
        public static string PrintCommentLabel {
            get {
                return ResourceManager.GetString("PrintCommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество копий.
        /// </summary>
        public static string PrintCopiesCountLabel {
            get {
                return ResourceManager.GetString("PrintCopiesCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расположение принтера.
        /// </summary>
        public static string PrinterLocationFieldLabel {
            get {
                return ResourceManager.GetString("PrinterLocationFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название принтера.
        /// </summary>
        public static string PrinterNameFieldLabel {
            get {
                return ResourceManager.GetString("PrinterNameFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формат.
        /// </summary>
        public static string PrintFormatLabel {
            get {
                return ResourceManager.GetString("PrintFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двусторонняя печать.
        /// </summary>
        public static string PrintTwoSideLabel {
            get {
                return ResourceManager.GetString("PrintTwoSideLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип.
        /// </summary>
        public static string PrintTypeLabel {
            get {
                return ResourceManager.GetString("PrintTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Секретный код.
        /// </summary>
        public static string SecretCodeFieldLabel {
            get {
                return ResourceManager.GetString("SecretCodeFieldLabel", resourceCulture);
            }
        }
    }
}
