//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ClientWeb.Printer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditViewResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditViewResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalPrint.Infrastructure.Resources.ClientWeb.Printer.EditViewResource", typeof(EditViewResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string CancelButtonLabel {
            get {
                return ResourceManager.GetString("CancelButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to День.
        /// </summary>
        public static string DayColumnHeader {
            get {
                return ResourceManager.GetString("DayColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключен.
        /// </summary>
        public static string DisabledFieldLabel {
            get {
                return ResourceManager.GetString("DisabledFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailFieldLabel {
            get {
                return ResourceManager.GetString("EmailFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование принтера.
        /// </summary>
        public static string FormHeaderEditText {
            get {
                return ResourceManager.GetString("FormHeaderEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый принтер.
        /// </summary>
        public static string FormHeaderNewText {
            get {
                return ResourceManager.GetString("FormHeaderNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование принтера.
        /// </summary>
        public static string FormTabEditTitle {
            get {
                return ResourceManager.GetString("FormTabEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление принтер.
        /// </summary>
        public static string FormTabNewTitle {
            get {
                return ResourceManager.GetString("FormTabNewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цветная.
        /// </summary>
        public static string IsColoredColumnHeader {
            get {
                return ResourceManager.GetString("IsColoredColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наличие.
        /// </summary>
        public static string IsSupportedColumnHeader {
            get {
                return ResourceManager.GetString("IsSupportedColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Двусторонняя.
        /// </summary>
        public static string IsTwoSidedColumnHeader {
            get {
                return ResourceManager.GetString("IsTwoSidedColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Долгота.
        /// </summary>
        public static string LatitudeFieldLabel {
            get {
                return ResourceManager.GetString("LatitudeFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение.
        /// </summary>
        public static string LocationFieldLabel {
            get {
                return ResourceManager.GetString("LocationFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Широта.
        /// </summary>
        public static string LongtitudeFieldLabel {
            get {
                return ResourceManager.GetString("LongtitudeFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыто.
        /// </summary>
        public static string OpenColumnHeader {
            get {
                return ResourceManager.GetString("OpenColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С.
        /// </summary>
        public static string OpenFromColumnHeader {
            get {
                return ResourceManager.GetString("OpenFromColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По.
        /// </summary>
        public static string OpenToColumnHeader {
            get {
                return ResourceManager.GetString("OpenToColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string PhoneFieldLabel {
            get {
                return ResourceManager.GetString("PhoneFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоимость.
        /// </summary>
        public static string PriceColumnHeader {
            get {
                return ResourceManager.GetString("PriceColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Услуги и цены.
        /// </summary>
        public static string PricingTableHeader {
            get {
                return ResourceManager.GetString("PricingTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string PrinterNameFieldLabel {
            get {
                return ResourceManager.GetString("PrinterNameFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string SaveButtolLabel {
            get {
                return ResourceManager.GetString("SaveButtolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расписание работы принтера.
        /// </summary>
        public static string ScheduleTableHeader {
            get {
                return ResourceManager.GetString("ScheduleTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Услуга.
        /// </summary>
        public static string ServiceColumnHeader {
            get {
                return ResourceManager.GetString("ServiceColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер.
        /// </summary>
        public static string SizeColumnHeader {
            get {
                return ResourceManager.GetString("SizeColumnHeader", resourceCulture);
            }
        }
    }
}
