//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ClientWeb.UserProfile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfirmPrintOrderViewResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfirmPrintOrderViewResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalPrint.Infrastructure.Resources.ClientWeb.UserRecievedPrintOrderList.Confirm" +
                            "PrintOrderViewResource", typeof(ConfirmPrintOrderViewResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ.
        /// </summary>
        public static string DocumentFieldLalel {
            get {
                return ResourceManager.GetString("DocumentFieldLalel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите секретный код.
        /// </summary>
        public static string EnterSecretCode {
            get {
                return ResourceManager.GetString("EnterSecretCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печать заказа.
        /// </summary>
        public static string FormTabTitle {
            get {
                return ResourceManager.GetString("FormTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные о заказе.
        /// </summary>
        public static string OrderInfo {
            get {
                return ResourceManager.GetString("OrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер заказа.
        /// </summary>
        public static string OrderNumberFieldLabel {
            get {
                return ResourceManager.GetString("OrderNumberFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоимость.
        /// </summary>
        public static string PriceFieldLalel {
            get {
                return ResourceManager.GetString("PriceFieldLalel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распечатать.
        /// </summary>
        public static string PrintButtonLabel {
            get {
                return ResourceManager.GetString("PrintButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение принтера.
        /// </summary>
        public static string PrinterLocationFieldLalel {
            get {
                return ResourceManager.GetString("PrinterLocationFieldLalel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название принтера.
        /// </summary>
        public static string PrinterNameFieldLabel {
            get {
                return ResourceManager.GetString("PrinterNameFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Секретный код.
        /// </summary>
        public static string SecretCodeFieldLabel {
            get {
                return ResourceManager.GetString("SecretCodeFieldLabel", resourceCulture);
            }
        }
    }
}
